# Generated by Django 3.2.3 on 2021-06-16 14:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=45, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/bethani/')),
                ('description', models.TextField(max_length=250, null=True)),
                ('available_status', models.BooleanField(default=True)),
                ('borrow_count', models.PositiveIntegerField(default=0)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(choices=[('N', 'Nepali'), ('E', 'English'), ('S', 'Sanskrit'), ('T', 'Tharu'), ('H', 'Hindi'), ('Ne', 'Newari'), ('O', 'Others')], default='N', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=7)),
                ('address', models.CharField(max_length=45)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('house_no', models.PositiveIntegerField()),
                ('profession', models.CharField(choices=[('A', 'Agriculture'), ('T', 'Teacher'), ('S', 'Student'), ('B', 'Business'), ('E', 'Employee')], max_length=15)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/bethani/profiles/')),
                ('account_activated', models.BooleanField(default=False)),
                ('books_borrowed', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_accept_date', models.CharField(default='-', max_length=60)),
                ('social_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(5)])),
                ('returned_date', models.DateField(auto_now_add=True)),
                ('borrower_note', models.TextField(max_length=250, null=True)),
                ('owner_comment', models.TextField(max_length=250, null=True)),
                ('book_borrowed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_borrowed_hist', to='club_bethani.book')),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_borrower_hist', to='club_bethani.reader')),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('borrow_accept', models.BooleanField(default=False)),
                ('book_received_by_borrower', models.BooleanField(default=False)),
                ('borrow_accept_date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(max_length=250, null=True)),
                ('returned', models.BooleanField(default=False)),
                ('book_borrowed', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_borrowed', to='club_bethani.book')),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_borrower', to='club_bethani.reader')),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='reader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Reader', to='club_bethani.reader'),
        ),
    ]
