# Generated by Django 3.2.4 on 2021-07-01 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_bethani', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='book_borrowed',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_borroweed', to='club_bethani.book'),
        ),
    ]
