# Generated by Django 3.2.3 on 2021-05-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_bethani', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrow_accept_date',
            field=models.CharField(default='-', max_length=60),
        ),
    ]
