# Generated by Django 3.2.4 on 2021-07-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_bethani', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('Nepali', 'Nepali'), ('English', 'English'), ('Sanskrit', 'Sanskrit'), ('Tharu', 'Tharu'), ('Hindi', 'Hindi'), ('Newari', 'Newari'), ('Others', 'Others')], default='Nepali', max_length=10),
        ),
        migrations.AlterField(
            model_name='reader',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7),
        ),
        migrations.AlterField(
            model_name='reader',
            name='profession',
            field=models.CharField(choices=[('Agriculture', 'Agriculture'), ('Teacher', 'Teacher'), ('Medical', 'Medical'), ('Business', 'Business'), ('Transportation', 'Transportation'), ('Finance', 'Finance'), ('Student', 'Student'), ('Engineering', 'Engineering'), ('Politics', 'Politics'), ('Religion', 'Religion')], max_length=15),
        ),
    ]
