# Generated by Django 3.2.3 on 2021-05-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_bethani', '0002_alter_borrow_borrow_accept_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrow_accept_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
