# Generated by Django 3.2.3 on 2021-05-31 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_bethani', '0004_alter_borrow_borrow_accept_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='borrow_accept_date',
        ),
    ]
