# Generated by Django 3.2.3 on 2021-05-31 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_bethani', '0008_borrow_borrow_accept_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='books_borrowed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reader',
            name='house_no',
            field=models.PositiveIntegerField(),
        ),
    ]
