# Generated by Django 3.2.3 on 2021-05-31 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_bethani', '0009_auto_20210531_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='borrow_accept_date',
        ),
    ]
