# Generated by Django 3.2.3 on 2021-05-31 02:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('club_bethani', '0010_remove_borrow_borrow_accept_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='borrow_accept_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
