# Generated by Django 3.2.3 on 2021-05-31 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_bethani', '0011_borrow_borrow_accept_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='book_received_by_borrower',
            field=models.BooleanField(default=False),
        ),
    ]
