# Generated by Django 3.2.3 on 2021-06-01 02:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_bethani', '0012_borrow_book_received_by_borrower'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocailRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(5)])),
                ('book_return_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(max_length=250, null=True)),
                ('book_returner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_book_borrower', to='club_bethani.reader')),
                ('returned_book', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_book_borrowed', to='club_bethani.book')),
            ],
            options={
                'ordering': ['-book_return_date'],
            },
        ),
    ]
