# Generated by Django 3.2.3 on 2021-06-01 02:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_bethani', '0013_socailrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socailrate',
            name='social_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
