# Generated by Django 3.2.3 on 2021-06-01 02:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_bethani', '0015_alter_socailrate_social_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowhistory',
            old_name='note',
            new_name='borrower_note',
        ),
        migrations.AddField(
            model_name='borrowhistory',
            name='owner_comment',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='borrowhistory',
            name='social_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.DeleteModel(
            name='SocailRate',
        ),
    ]
