# Generated by Django 3.2.3 on 2021-06-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_bethani', '0016_auto_20210601_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrow_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
